config/routes.rb
Rails.application.routes.draw do
  get 'register/info1'

  get 'register/info2'

  get 'visitor/main'

  resources :posts
  resources :classifications
  resources :inquiries
  resources :products
  resources :categorie1s
  resources :categorie2s
  resources :categorie3s
  resources :products
  resources :orders
  resources :followers
  resources :baskets
  resources :products
  devise_for :users, :controllers => { omniauth_callbacks: 'user/omniauth_callbacks'}
  root 'welcome#index'
  post 'welcome/find_categorie2'
  post 'welcome/find_categorie3'
  get 'welcome/product/:id' => 'welcome#product'
  get 'welcome/page_scroll' => 'welcome#page_scroll', as: 'scroll'
  post 'welcome/add_cart'
  get 'welcome/cart'
  delete 'welcome/delete_product/:id' => 'welcome#delete_product'
  post 'welcome/add_order'
  get 'welcome/order'
  get 'welcome/post/:id' => 'welcome#post'
  get 'welcome/inquiry'
  post 'welcome/inquiryCreate'
  get 'welcome/myInquiry'
  post 'likes/update'
  post 'likes/count'
  delete 'welcome/delete_inquiry/:id' => 'welcome#delete_inquiry'
  get 'welcome/show_product1/:id' => 'welcome#show_product1'
  get 'welcome/show_product2/:id' => 'welcome#show_product2'
  get 'welcome/show_product3/:id' => 'welcome#show_product3'
  post 'welcome/orderCreate'
  delete 'welcome/delete_order/:id' => 'welcome#delete_order'

end

app/models/basket.rb
class Basket < ActiveRecord::Base
	belongs_to :user
	belongs_to :product
	validates :user, :product, presence: true
end

app/models/categorie1.rb
class Categorie1 < ActiveRecord::Base
	has_many :products, dependent: :destroy
	has_many :categorie2s, dependent: :destroy
	validates :content, presence: true
end

app/models/categorie2.rb
class Categorie2 < ActiveRecord::Base
	belongs_to :categorie1
	has_many :products, dependent: :destroy
	has_many :categorie3s, dependent: :destroy
	validates :categorie1, :content, presence: true
end

app/models/categorie3.rb
class Categorie3 < ActiveRecord::Base
	belongs_to :categorie2
	has_many :products, dependent: :destroy
	validates :categorie2, :content, presence: true

end

app/models/classification.rb
class Classification < ActiveRecord::Base
	has_many :posts, dependent: :destroy
end

app/models/follower.rb
class Follower < ActiveRecord::Base
	belongs_to :user
	belongs_to :product
	validates :user, :product, presence: true
end

app/models/identity.rb
# app/models/identity.rb

class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
  belongs_to :user
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	#belongs_to :product
	serialize :product_ids
	serialize :basket_ids 
	serialize :numbers
	serialize :donations
	validates :user, :product_ids, :numbers, :product_price, :total_price, :address, :payment, :agreement ,presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  resourcify
  include Authority::Abilities
  belongs_to :classification
  belongs_to :user
  validates :title, :content, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :baskets, dependent: :destroy
  	has_many :followers, dependent: :destroy
  	#has_many :orders, dependent: :destroy
  	belongs_to :categorie1
  	belongs_to :categorie2
  	belongs_to :categorie3
  	validates :img, :name, :price, :weight, :categorie1, :categorie2, :categorie3, :content, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  include Authority::UserAbilities
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :posts, dependent: :destroy
  has_many :baskets, dependent: :destroy
  has_many :followers, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :inquiries, dependent: :destroy

  #validates :agreement, :information, presence: true


  after_create :set_default_role, if: Proc.new { User.count > 1 }

  def self.find_for_oauth(auth, signed_in_resource = nil)
    # user와 identity가 nil이 아니라면 받는다

    identity = Identity.find_for_oauth(auth)
    user = signed_in_resource ? signed_in_resource : identity.user

    # user가 nil이라면 새로 만든다.

    if user.nil?

      # 이미 있는 이메일인지 확인한다.

      email = auth.info.email
      user = User.where(:email => email).first

      unless self.where(email: auth.info.email).exists?
        # 없다면 새로운 데이터를 생성한다.

        if user.nil?
          # 카카오는 email을 제공하지 않음

          if auth.provider == "kakao"
            # provider(회사)별로 데이터를 제공해주는 hash의 이름이 다릅니다.

            # 각각의 omnaiuth별로 auth hash가 어떤 경로로, 어떤 이름으로 제공되는지 확인하고 설정해주세요.
            user = User.new(
              profile_img: auth.info.image,
              # 이 부분은 AWS S3와 연동할 때 프로필 이미지를 저장하기 위해 필요한 부분입니다.

              # remote_profile_img_url: auth.info.image.gsub('http://','https://'),

              password: Devise.friendly_token[0,20]
            )

          else
            user = User.new(
              email: auth.info.email,
              profile_img: auth.info.image,
              # remote_profile_img_url: auth.info.image.gsub('http://','https://'),

              password: Devise.friendly_token[0,20]
            )
          end
          user.save!
        end
      end
    end

    if identity.user != user
      identity.user = user
      binding.pry
      identity.save!
    end
    user

  end

  # email이 없어도 가입이 되도록 설정

  def email_required?
    false
  end
  
  private

  def set_default_role
    add_role :user
  end

end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :set_basket, only: [:show, :edit, :update, :destroy]
  before_action :admin
  # GET /baskets
  # GET /baskets.json
  def index
    @baskets = Basket.all
  end

  # GET /baskets/1
  # GET /baskets/1.json
  def show
  end

  # GET /baskets/new
  def new
    @basket = Basket.new
  end

  # GET /baskets/1/edit
  def edit
  end

  # POST /baskets
  # POST /baskets.json
  def create
    @basket = Basket.new(basket_params)

    respond_to do |format|
      if @basket.save
        format.html { redirect_to @basket, notice: 'Basket was successfully created.' }
        format.json { render :show, status: :created, location: @basket }
      else
        format.html { render :new }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /baskets/1
  # PATCH/PUT /baskets/1.json
  def update
    respond_to do |format|
      if @basket.update(basket_params)
        format.html { redirect_to @basket, notice: 'Basket was successfully updated.' }
        format.json { render :show, status: :ok, location: @basket }
      else
        format.html { render :edit }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /baskets/1
  # DELETE /baskets/1.json
  def destroy
    @basket.destroy
    respond_to do |format|
      format.html { redirect_to baskets_url, notice: 'Basket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_basket
      @basket = Basket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def basket_params
      params.require(:basket).permit(:user_id, :product_id, :number, :donation)
    end
    def admin
      unless current_user
        redirect_to '/'
      end
      if current_user
        unless current_user.roles == "Admin"
          redirect_to '/'
        end
      end
    end
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/visitor_helper.rb
module VisitorHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/baskets/_form.html.erb
<%= form_for(@basket) do |f| %>
  <% if @basket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@basket.errors.count, "error") %> prohibited this basket from being saved:</h2>

      <ul>
      <% @basket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :donation %><br>
    <%= f.check_box :donation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/baskets/edit.html.erb
<h1>Editing Basket</h1>

<%= render 'form' %>

<%= link_to 'Show', @basket %> |
<%= link_to 'Back', baskets_path %>

app/views/baskets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Baskets</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Product</th>
      <th>Number</th>
      <th>Donation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @baskets.each do |basket| %>
      <tr>
        <td><%= basket.user %></td>
        <td><%= basket.product %></td>
        <td><%= basket.number %></td>
        <td><%= basket.donation %></td>
        <td><%= link_to 'Show', basket %></td>
        <td><%= link_to 'Edit', edit_basket_path(basket) %></td>
        <td><%= link_to 'Destroy', basket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Basket', new_basket_path %>

app/views/baskets/new.html.erb
<h1>New Basket</h1>

<%= render 'form' %>

<%= link_to 'Back', baskets_path %>

app/views/baskets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @basket.user %>
</p>

<p>
  <strong>Product:</strong>
  <%= @basket.product %>
</p>

<p>
  <strong>Number:</strong>
  <%= @basket.number %>
</p>

<p>
  <strong>Donation:</strong>
  <%= @basket.donation %>
</p>

<%= link_to 'Edit', edit_basket_path(@basket) %> |
<%= link_to 'Back', baskets_path %>