config/routes.rb
Rails.application.routes.draw do
  get 'register/info1'

  get 'register/info2'

  get 'visitor/main'

  resources :posts
  resources :classifications
  resources :inquiries
  resources :products
  resources :categorie1s
  resources :categorie2s
  resources :categorie3s
  resources :products
  resources :orders
  resources :followers
  resources :baskets
  resources :products
  devise_for :users, :controllers => { omniauth_callbacks: 'user/omniauth_callbacks'}
  root 'welcome#index'
  post 'welcome/find_categorie2'
  post 'welcome/find_categorie3'
  get 'welcome/product/:id' => 'welcome#product'
  get 'welcome/page_scroll' => 'welcome#page_scroll', as: 'scroll'
  post 'welcome/add_cart'
  get 'welcome/cart'
  delete 'welcome/delete_product/:id' => 'welcome#delete_product'
  post 'welcome/add_order'
  get 'welcome/order'
  get 'welcome/post/:id' => 'welcome#post'
  get 'welcome/inquiry'
  post 'welcome/inquiryCreate'
  get 'welcome/myInquiry'
  post 'likes/update'
  post 'likes/count'
  delete 'welcome/delete_inquiry/:id' => 'welcome#delete_inquiry'
  get 'welcome/show_product1/:id' => 'welcome#show_product1'
  get 'welcome/show_product2/:id' => 'welcome#show_product2'
  get 'welcome/show_product3/:id' => 'welcome#show_product3'
  post 'welcome/orderCreate'
  delete 'welcome/delete_order/:id' => 'welcome#delete_order'

end

app/models/categorie1.rb
class Categorie1 < ActiveRecord::Base
	has_many :products, dependent: :destroy
	has_many :categorie2s, dependent: :destroy
	validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  include Authority::UserAbilities
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :posts, dependent: :destroy
  has_many :baskets, dependent: :destroy
  has_many :followers, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :inquiries, dependent: :destroy

  #validates :agreement, :information, presence: true


  after_create :set_default_role, if: Proc.new { User.count > 1 }

  def self.find_for_oauth(auth, signed_in_resource = nil)
    # user와 identity가 nil이 아니라면 받는다

    identity = Identity.find_for_oauth(auth)
    user = signed_in_resource ? signed_in_resource : identity.user

    # user가 nil이라면 새로 만든다.

    if user.nil?

      # 이미 있는 이메일인지 확인한다.

      email = auth.info.email
      user = User.where(:email => email).first

      unless self.where(email: auth.info.email).exists?
        # 없다면 새로운 데이터를 생성한다.

        if user.nil?
          # 카카오는 email을 제공하지 않음

          if auth.provider == "kakao"
            # provider(회사)별로 데이터를 제공해주는 hash의 이름이 다릅니다.

            # 각각의 omnaiuth별로 auth hash가 어떤 경로로, 어떤 이름으로 제공되는지 확인하고 설정해주세요.
            user = User.new(
              profile_img: auth.info.image,
              # 이 부분은 AWS S3와 연동할 때 프로필 이미지를 저장하기 위해 필요한 부분입니다.

              # remote_profile_img_url: auth.info.image.gsub('http://','https://'),

              password: Devise.friendly_token[0,20]
            )

          else
            user = User.new(
              email: auth.info.email,
              profile_img: auth.info.image,
              # remote_profile_img_url: auth.info.image.gsub('http://','https://'),

              password: Devise.friendly_token[0,20]
            )
          end
          user.save!
        end
      end
    end

    if identity.user != user
      identity.user = user
      binding.pry
      identity.save!
    end
    user

  end

  # email이 없어도 가입이 되도록 설정

  def email_required?
    false
  end
  
  private

  def set_default_role
    add_role :user
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]
  def index
  	@categorie1 = Categorie1.all
  	@product = Product.order("created_at DESC").page(params[:page])
    if current_user
      @follower = Follower.where(user_id: current_user.id)
    end
    @list= Follower.group(:product_id).count
    @best3= Follower.group(:product_id).count
    @sort = @best3.sort_by {|_key, value| value}
    @result = @sort.reverse.to_h 
    @array = Array.new
    @result.each do |key, value|
      @array << key
    end
    #@best3 = Product.find(@array[0].to_i, @array[1].to_i, @array[2].to_i)
  end
  def show_product1
    @categorie1 = Categorie1.all
    @product = Product.where(categorie1: params[:id]).page(params[:page])
    @categorie = Categorie2.where(categorie1: params[:id])
    @load = Categorie1.find(params[:id])
    if current_user
      @follower = Follower.where(user_id: current_user.id)
    end
    @list= Follower.group(:product_id).count
    @best3= Follower.group(:product_id).count
    @sort = @best3.sort_by {|_key, value| value}
    @result = @sort.reverse.to_h 
    @array = Array.new
    @result.each do |key, value|
      @array << key
    end
    #@
  end
  def show_product2
    @categorie1 = Categorie1.all
    @product = Product.where(categorie2: params[:id]).page(params[:page])
    @categorie = Categorie3.where(categorie2: params[:id])
    @load = Categorie2.find(params[:id])
    if current_user
      @follower = Follower.where(user_id: current_user.id)
    end
    @list= Follower.group(:product_id).count
    @best3= Follower.group(:product_id).count
    @sort = @best3.sort_by {|_key, value| value}
    @result = @sort.reverse.to_h 
    @array = Array.new
    @result.each do |key, value|
      @array << key
    end
    #@
  end
  def show_product3
    @categorie1 = Categorie1.all
    @product = Product.where(categorie3: params[:id]).page(params[:page])
    @load = Categorie3.find(params[:id])
    if current_user
      @follower = Follower.where(user_id: current_user.id)
    end
    @list= Follower.group(:product_id).count
    @best3= Follower.group(:product_id).count
    @sort = @best3.sort_by {|_key, value| value}
    @result = @sort.reverse.to_h 
    @array = Array.new
    @result.each do |key, value|
      @array << key
    end
    #@
  end
  def find_categorie2
  	categorie1 = Categorie1.find_by(content: params[:categorie1])
  	@categorie2 = Categorie2.where(categorie1_id: categorie1.id)

  	render layout: false
  end
  def find_categorie3
  	categorie2 = Categorie2.find_by(content: params[:categorie2])
  	@categorie3 = Categorie3.where(categorie2_id: categorie2.id)

  	render layout: false
  end
  def page_scroll
    @product = Product.order("created_at DESC").page(params[:page])
  end
  def add_cart
    Basket.create!(user_id: current_user.id, product_id: params[:product_id])
    redirect_to '/'
  end
  def cart
    @baskets = Basket.where(user_id: current_user.id).order("created_at DESC")
  end
  def delete_product
    @basket = Basket.find(params[:id])
    @basket.destroy
    redirect_to :back
  end
  def add_order
    ids = params[:id_list].rstrip.split()
    #@product_ids = ""
    @product_ids = []
    @basket_ids = []
    @product_price = 0
    @donation_price = 0
    @total_price = 0
    #@total_weight = 0
    #@numbers = ""
    @numbers = []
    #@donations = ""
    @donations = []
    ids.each do |id|
      stId = id.to_s
      num = "num" + stId
      @basket = Basket.find(id)
      #@product_ids = @product_ids + @basket.product_id.to_s + " "
      @basket_ids.append(@basket.id.to_s)
      @product_ids.append(@basket.product_id.to_s)
      number = params[num]
      #@numbers = @numbers + number + " "
      @numbers.append(number)
      @product_price = @product_price + @basket.product.price * number.to_i
      @total_price = @total_price + @basket.product.price * number.to_i
      #@total_weight = @total_weight + @basket.product.weight * number.to_i
      if params[stId] == "true"
        #@donations = @donations + "true" + " " 
        @donations.append("true")
        @donation_price = @donation_price + @basket.product.price
        @total_price = @total_price + @basket.product.price
        #@total_weight = @total_weight + @basket.product.weight * number.to_i
      else
        #@donations = @donations + "false" + " "     
        @donations.append("false")
      end
      #@basket.destroy
    end  
    @order = Order.new
    #@order = Order.create(user_id: current_user.id, product_ids: @product_ids, numbers: @numbers, donations: @donations, product_price: @product_price, donation_price: @donation_price, total_price: @total_price, address: params[:address], payment: "배송준비중", invoice: "준비중", parcel: "쿠팡", parcel_number: "01000000000")  
    @address = Order.where(user_id: current_user).group(:address, :address_detail, :address_number)
  end

  def orderCreate
    @order = Order.create(user_id: current_user.id, name: params[:order][:name], phone: params[:order][:phone], phone2: params[:order][:phone2], product_ids: params[:order][:product_ids], numbers: params[:order][:numbers], donations: params[:order][:donations], product_price: params[:order][:product_price], donation_price: params[:order][:donation_price], total_price: params[:order][:total_price], address: params[:order][:address], address_detail: params[:order][:address_detail], address_number: params[:order][:address_number], payment: "입금 대기중", invoice: "준비중", parcel: "쿠팡", parcel_number: "01000000000", payment_option: params[:order][:payment_option],agreement: params[:order][:agreement],content: params[:order][:content] )  
    @basket_ids = params[:order][:basket_ids].split()
    if @basket_ids[1]
      @basket_ids.each do |basket_id|
        @basket = Basket.find(basket_id)
        @basket.destroy
      end
    else
      @basket = Basket.find(@basket_ids[0])
      @basket.destroy
    end
    redirect_to '/welcome/order'
  end
  def order
    @orders = Order.where(user_id: current_user.id).order("created_at DESC")
  end
  def post
    @posts = Post.where(classification_id: params[:id])
  end
  def inquiry
    @inquiry = Inquiry.new
    @classification = Classification.select(:category)
  end
  def inquiryCreate
    Inquiry.create!(email: params[:inquiry][:email], title: params[:inquiry][:title], content: params[:inquiry][:content], category: params[:inquiry][:category], answer: "답변 준비중", user_id: current_user.id)
    redirect_to '/welcome/myInquiry'
  end
  def myInquiry
    @inquiries = Inquiry.where(user_id: current_user.id).order("created_at DESC") 
  end
  def delete_inquiry
    @inquiry = Inquiry.find(params[:id])
    @inquiry.destroy
    redirect_to '/welcome/myInquiry'
  end
  def delete_order
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to '/welcome/order'
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/cart.html.erb
<%= form_tag({ controller: :welcome, action: :add_order }) do %>
	<% @baskets.each do |basket| %>
		<label><%= check_box_tag 'id', "#{basket.id}", true, class: 'checkbox', id: 'chkBox' %></label>
		<!-- <input type='checkbox' class='mycheck' value="<%= basket.id %>" />, -->
		<img src="<%= basket.product.img %>" width="100" height="100">,<%= basket.product.name %>, <%= basket.product.price %>, <%= basket.product.weight %>, <%= Categorie1.find(basket.product.categorie1_id).content %>, <%= Categorie2.find(basket.product.categorie2_id).content %>, <%= Categorie3.find(basket.product.categorie3_id).content %>, <%= basket.product.content %>,
		<!-- <button class="delete" value="<%= basket.id %>">delete</button> -->
		<%= number_field_tag "num#{basket.id}", 1, max: 99 %>
		<label>donation : <%= check_box_tag "#{basket.id}", true, false %></label>,
		<%= link_to "delete", "/welcome/delete_product/#{basket.id}", method: :delete, data: { confirm: "Are you sure?" } %>
		<br>
	<% end %>
	<hr>
	<div align="center">
		<%= hidden_field_tag 'id_list', '', class: 'id_list' %>
	</div>
	<br>
	<div align="center">
		<input type="submit" class="xxx">
	</div>	
<% end %>

<script>
  	$(function() {
  		var id = '';
  		$('.xxx').click(function(){
	   		$('#chkBox:checked').each(function() {
	   			id = id + $(this).val() + ' ';
   			});
   			$('#id_list').attr('value', id);	
	   	});	
  	});
	
</script>

app/views/welcome/find_categorie2.html.erb
<% @categorie2.each do |categorie2| %>
	<button class="categorie2" value="<%= categorie2.content %>"><%= categorie2.content %></button>
<% end %>

<script>
	$(function() {
	    $('.categorie2').click(function(){
	      categorie2 = this.value;
	      $.ajax({
	        method: "POST",
	        dataType: 'html',
	        url: "/welcome/find_categorie3",
	        data: { categorie2: categorie2 },
	        success: function(data){

	          $("#ajax2").html(data)
	          
	        },
	        error: function(){
	          alert("실패")
	        }
	      });
	    });
	});
</script>

app/views/welcome/find_categorie3.html.erb
<hr>
<% @categorie3.each do |categorie3| %>
	<%= link_to categorie3.content, "/welcome/product/#{categorie3.id}" %><br>
	<!-- <button class="categorie3" value="<%= categorie3.content %>"><%= categorie3.content %></button> -->
<% end %>

app/views/welcome/index.html.erb
 <script>
  $(function() {
    var page_scroll_index = 2;
    $(window).scroll(function() {
       // 진짜 중요한거!!!!!
       if($(window).scrollTop() >= $(document).height() - $(window).height()) {
         $.ajax({
           method: "GET",
          url: "<%= scroll_path %>",
          data: {
            page: page_scroll_index++
          }
         })
       }
    });  
  });
</script>


<div class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <!-- <button type="button" class="navbar-toggle" data-toggle="collapse2" data-target=".navbar-collapse"> -->
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">categorie</a>
    </div>
    <div class="navbar-collapse collapse2">
	  <ul class="nav navbar-nav">
	      <li class="dropdown">
	        <a href="#" class="dropdown-toggle" data-toggle="dropdown">categorie1<b class="caret"></b></a>
	        <ul class="dropdown-menu">
	        	<% @categorie1.each do |categorie1| %>
              <li><%= link_to categorie1.content, "/welcome/show_product1/#{categorie1.id}" %></li>
		        <% end %>
	        </ul>
	      </li>
	  </ul>
	</div><!--/.nav-collapse -->
  </div>
</div>
<div id="ajax">
</div>
<div id="ajax2">
</div>
<h2>Best4</h2>
<% if @array[3] %>
  <% for i in (0..3) %>
    <div>
      <% product = Product.find(@array[i]) %>
      <img src="<%= product.img %>" width="100" height="100">,
      <%= product.name %>, <%= product.price %>, 
      <%= product.weight %>, 
      <%= Categorie1.find(product.categorie1_id).content %>, 
      <%= Categorie2.find(product.categorie2_id).content %>, 
      <%= Categorie3.find(product.categorie3_id).content %>, 
      <%= product.content %> 
      좋아요 수 : <span class="<%= product.id %>"><%= @list[product.id] %></span>
      <button class="add" value="<%= product.id %>">add Cart</button>
      <button class="like" value="<%= product.id %>">
        <% if current_user and Follower.find_by(user_id: current_user.id, product_id: product.id) %>
            좋아요
        <% else %>
          싫어요
        <% end %>
      </button>
      <br>
      <%#= paginate @product %>
    </div>
  <% end %>
<% end %>
<hr>
<hr>
<h2>Product</h2>
<div id="boxx">
	<% @product.each do |product| %>
		<img src="<%= product.img %>" width="100" height="100">,
    <%= product.name %>, <%= product.price %>, 
    <%= product.weight %>, 
    <%= Categorie1.find(product.categorie1_id).content %>, 
    <%= Categorie2.find(product.categorie2_id).content %>, 
    <%= Categorie3.find(product.categorie3_id).content %>, 
    <%= product.content %> 
    좋아요 수 : <span class="<%= product.id %>"><%= @list[product.id] %></span>
    <button class="add" value="<%= product.id %>">add Cart</button>
    <button class="like" value="<%= product.id %>">
      <% if current_user and Follower.find_by(user_id: current_user.id, product_id: product.id) %>
          좋아요
      <% else %>
        싫어요
      <% end %>
    </button>
    <br>
	<% end %>
  <%#= paginate @product %>
</div>


<script>
  $(function() {
    $('.categorie1').click(function(){
      categorie1 = this.value;
      $.ajax({
        method: "POST",
        dataType: 'html',
        url: "/welcome/find_categorie2",
        data: { categorie1: categorie1 },
        success: function(data){

          $("#ajax").html(data)
          
        },
        error: function(){
          alert("실패")
        }
      });
    });
  });
</script>
<script>
  $(function() {
    $('.add').click(function(){
      product_id = this.value;
      $.ajax({
        method: "POST",
        url: "/welcome/add_cart",
        data: { product_id: product_id },
        success: function(){

          alert("추가 되었습니다.")
          
        },
        error: function(){
          alert("실패")
        }
      });
    });
  });
</script>
<script>
    $(function(){
        $('.like').click(function(){
            product_id = this.value;
            $.ajax({
                method: "POST",
                dataType: 'html',
                url: "/likes/update",
                data: { product_id: product_id },
                success: function(data){
                  $(".like[value='"+product_id+"']").html(data);
                },
                error: function(){
                alert("로그인이 필요합니다 !!!");
                }
            });
            $.ajax({
                method: "POST",
                dataType: 'html',
                url: "/likes/count",
                data: { product_id: product_id },
                success: function(data){
                  $("."+product_id).html(data);
                },
                error: function(){
                alert("로그인이 필요합니다 !!!");
                }
            });
        });

    });
</script>

app/views/welcome/myInquiry.html.erb
<% @inquiries.each do |inquiry| %>
	<%= inquiry.email %>
	<%= inquiry.title %>
	<%= inquiry.content %>
	<%= inquiry.category %>
	<%= inquiry.answer %>
	<%= link_to "delete", "/welcome/delete_inquiry/#{inquiry.id}", method: :delete, data: { confirm: "Are you sure?" } %>
	<br>
<% end %>
<div align="center">
	<%= link_to "1:1 문의", "/welcome/inquiry" %>
</div>

app/views/welcome/show_product1.html.erb
 <script>
  $(function() {
    var page_scroll_index = 2;
    $(window).scroll(function() {
       // 진짜 중요한거!!!!!
       if($(window).scrollTop() >= $(document).height() - $(window).height()) {
         $.ajax({
           method: "GET",
          url: "<%= scroll_path %>",
          data: {
            page: page_scroll_index++
          }
         })
       }
    });  
  });
</script>


<div class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <!-- <button type="button" class="navbar-toggle" data-toggle="collapse2" data-target=".navbar-collapse"> -->
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">categorie</a>
    </div>
    <div class="navbar-collapse collapse2">
    <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">categorie1<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% @categorie1.each do |categorie1| %>
              <li><%= link_to categorie1.content, "/welcome/show_product1/#{categorie1.id}" %></li>
            <% end %>
          </ul>
        </li>
    </ul>
  </div><!--/.nav-collapse -->
  </div>
</div>
<div id="ajax">
</div>
<div id="ajax2">
</div>
<div>
  <%= @load.content %>
  <br>
  <% @categorie.each do |categorie| %>
    <%= link_to categorie.content, "/welcome/show_product2/#{categorie.id}" %>
  <% end %>
</div>
<h2>Best4</h2>
<% if @array[3] %>
  <% for i in (0..3) %>
    <div>
      <% product = Product.find(@array[i]) %>
      <img src="<%= product.img %>" width="100" height="100">,
      <%= product.name %>, <%= product.price %>, 
      <%= product.weight %>, 
      <%= Categorie1.find(product.categorie1_id).content %>, 
      <%= Categorie2.find(product.categorie2_id).content %>, 
      <%= Categorie3.find(product.categorie3_id).content %>, 
      <%= product.content %> 
      좋아요 수 : <span class="<%= product.id %>"><%= @list[product.id] %></span>
      <button class="add" value="<%= product.id %>">add Cart</button>
      <button class="like" value="<%= product.id %>">
        <% if current_user and Follower.find_by(user_id: current_user.id, product_id: product.id) %>
            좋아요
        <% else %>
          싫어요
        <% end %>
      </button>
      <br>
      <%#= paginate @product %>
    </div>
  <% end %>
<% end %>
<hr>
<hr>
<h2>Product</h2>
<div id="boxx">
  <% @product.each do |product| %>
    <img src="<%= product.img %>" width="100" height="100">,
    <%= product.name %>, <%= product.price %>, 
    <%= product.weight %>, 
    <%= Categorie1.find(product.categorie1_id).content %>, 
    <%= Categorie2.find(product.categorie2_id).content %>, 
    <%= Categorie3.find(product.categorie3_id).content %>, 
    <%= product.content %> 
    좋아요 수 : <span class="<%= product.id %>"><%= @list[product.id] %></span>
    <button class="add" value="<%= product.id %>">add Cart</button>
    <button class="like" value="<%= product.id %>">
      <% if current_user and Follower.find_by(user_id: current_user.id, product_id: product.id) %>
          좋아요
      <% else %>
        싫어요
      <% end %>
    </button>
    <br>
  <% end %>
  <%#= paginate @product %>
</div>


<script>
  $(function() {
    $('.categorie1').click(function(){
      categorie1 = this.value;
      $.ajax({
        method: "POST",
        dataType: 'html',
        url: "/welcome/find_categorie2",
        data: { categorie1: categorie1 },
        success: function(data){

          $("#ajax").html(data)
          
        },
        error: function(){
          alert("실패")
        }
      });
    });
  });
</script>
<script>
  $(function() {
    $('.add').click(function(){
      product_id = this.value;
      $.ajax({
        method: "POST",
        url: "/welcome/add_cart",
        data: { product_id: product_id },
        success: function(){

          alert("추가 되었습니다.")
          
        },
        error: function(){
          alert("실패")
        }
      });
    });
  });
</script>
<script>
    $(function(){
        $('.like').click(function(){
            product_id = this.value;
            $.ajax({
                method: "POST",
                dataType: 'html',
                url: "/likes/update",
                data: { product_id: product_id },
                success: function(data){
                  $(".like[value='"+product_id+"']").html(data);
                },
                error: function(){
                alert("무엇인가 잘못 되엇다 !!!");
                }
            });
            $.ajax({
                method: "POST",
                dataType: 'html',
                url: "/likes/count",
                data: { product_id: product_id },
                success: function(data){
                  $("."+product_id).html(data);
                },
                error: function(){
                alert("무엇인가 잘못 되엇다 !!!");
                }
            });
        });

    });
</script>

app/views/welcome/show_product2.html.erb
 <script>
  $(function() {
    var page_scroll_index = 2;
    $(window).scroll(function() {
       // 진짜 중요한거!!!!!
       if($(window).scrollTop() >= $(document).height() - $(window).height()) {
         $.ajax({
           method: "GET",
          url: "<%= scroll_path %>",
          data: {
            page: page_scroll_index++
          }
         })
       }
    });  
  });
</script>


<div class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <!-- <button type="button" class="navbar-toggle" data-toggle="collapse2" data-target=".navbar-collapse"> -->
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">categorie</a>
    </div>
    <div class="navbar-collapse collapse2">
    <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">categorie1<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% @categorie1.each do |categorie1| %>
              <li><%= link_to categorie1.content, "/welcome/show_product1/#{categorie1.id}" %></li>
            <% end %>
          </ul>
        </li>
    </ul>
  </div><!--/.nav-collapse -->
  </div>
</div>
<div id="ajax">
</div>
<div id="ajax2">
</div>
<div>
  <%= @load.categorie1.content %> -> <%= @load.content %>
  <br>
  <% @categorie.each do |categorie| %>
    <%= link_to categorie.content, "/welcome/show_product3/#{categorie.id}" %>
  <% end %>
</div>
<h2>Best4</h2>
<% if @array[3] %>
  <% for i in (0..3) %>
    <div>
      <% product = Product.find(@array[i]) %>
      <img src="<%= product.img %>" width="100" height="100">,
      <%= product.name %>, <%= product.price %>, 
      <%= product.weight %>, 
      <%= Categorie1.find(product.categorie1_id).content %>, 
      <%= Categorie2.find(product.categorie2_id).content %>, 
      <%= Categorie3.find(product.categorie3_id).content %>, 
      <%= product.content %> 
      좋아요 수 : <span class="<%= product.id %>"><%= @list[product.id] %></span>
      <button class="add" value="<%= product.id %>">add Cart</button>
      <button class="like" value="<%= product.id %>">
        <% if current_user and Follower.find_by(user_id: current_user.id, product_id: product.id) %>
            좋아요
        <% else %>
          싫어요
        <% end %>
      </button>
      <br>
      <%#= paginate @product %>
    </div>
  <% end %>
<% end %>
<hr>
<hr>
<h2>Product</h2>
<div id="boxx">
  <% @product.each do |product| %>
    <img src="<%= product.img %>" width="100" height="100">,
    <%= product.name %>, <%= product.price %>, 
    <%= product.weight %>, 
    <%= Categorie1.find(product.categorie1_id).content %>, 
    <%= Categorie2.find(product.categorie2_id).content %>, 
    <%= Categorie3.find(product.categorie3_id).content %>, 
    <%= product.content %> 
    좋아요 수 : <span class="<%= product.id %>"><%= @list[product.id] %></span>
    <button class="add" value="<%= product.id %>">add Cart</button>
    <button class="like" value="<%= product.id %>">
      <% if current_user and Follower.find_by(user_id: current_user.id, product_id: product.id) %>
          좋아요
      <% else %>
        싫어요
      <% end %>
    </button>
    <br>
  <% end %>
  <%#= paginate @product %>
</div>


<script>
  $(function() {
    $('.categorie1').click(function(){
      categorie1 = this.value;
      $.ajax({
        method: "POST",
        dataType: 'html',
        url: "/welcome/find_categorie2",
        data: { categorie1: categorie1 },
        success: function(data){

          $("#ajax").html(data)
          
        },
        error: function(){
          alert("실패")
        }
      });
    });
  });
</script>
<script>
  $(function() {
    $('.add').click(function(){
      product_id = this.value;
      $.ajax({
        method: "POST",
        url: "/welcome/add_cart",
        data: { product_id: product_id },
        success: function(){

          alert("추가 되었습니다.")
          
        },
        error: function(){
          alert("실패")
        }
      });
    });
  });
</script>
<script>
    $(function(){
        $('.like').click(function(){
            product_id = this.value;
            $.ajax({
                method: "POST",
                dataType: 'html',
                url: "/likes/update",
                data: { product_id: product_id },
                success: function(data){
                  $(".like[value='"+product_id+"']").html(data);
                },
                error: function(){
                alert("무엇인가 잘못 되엇다 !!!");
                }
            });
            $.ajax({
                method: "POST",
                dataType: 'html',
                url: "/likes/count",
                data: { product_id: product_id },
                success: function(data){
                  $("."+product_id).html(data);
                },
                error: function(){
                alert("무엇인가 잘못 되엇다 !!!");
                }
            });
        });

    });
</script>